# Generated by Django 3.0.2 on 2020-02-27 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mp3', '0002_auto_20200227_1052'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='trending',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no')], max_length=200, null=True),
        ),
    ]
