# Generated by Django 3.0.2 on 2020-03-17 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mp3', '0003_song_trending'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('email', models.CharField(max_length=200, null=True)),
                ('message', models.CharField(max_length=400, null=True)),
            ],
        ),
    ]
