# Generated by Django 3.0.2 on 2020-03-17 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mp3', '0005_auto_20200317_1322'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='album',
        ),
        migrations.RemoveField(
            model_name='song',
            name='country',
        ),
        migrations.RemoveField(
            model_name='song',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='song',
            name='trending',
        ),
    ]
