# Generated by Django 3.0.2 on 2020-03-17 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mp3', '0006_auto_20200317_1404'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='Messages',
        ),
    ]
