# Generated by Django 3.0.2 on 2020-03-17 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mp3', '0007_auto_20200317_2138'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
